# Generated by Django 4.1.7 on 2023-02-21 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='post title', max_length=255, verbose_name='title')),
                ('text', tinymce.models.HTMLField(blank=True, help_text='post text', max_length=4000, null=True, verbose_name='text')),
                ('posted', models.DateTimeField(auto_now_add=True, help_text='post created', verbose_name='posted')),
                ('updated', models.DateTimeField(auto_now=True, help_text='post updated', verbose_name='updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ManyToManyField(help_text='select categories for this post', to='blog.category', verbose_name='categories')),
            ],
            options={
                'ordering': ['posted'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='comments text', max_length=1000, verbose_name='text')),
                ('posted', models.DateTimeField(auto_now_add=True, help_text='comment posted', verbose_name='posted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='post')),
            ],
            options={
                'ordering': ['posted'],
            },
        ),
    ]
