# Generated by Django 4.1.7 on 2023-02-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default='about author', help_text='about text', max_length=500, verbose_name='about'),
            preserve_default=False,
        ),
    ]
